version: '3.8'

services:
  db:
    image: postgres:15
    container_name: kodix-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kodix
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-nest-backend
    container_name: kodix-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node dist/main"
volumes:
  postgres_data:
