name: CI & Deploy Backend to EC2

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build project
        run: yarn build

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: volodymyrsulik/backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🧹 Stop old docker container (if exist)"
            docker stop backend-app || true
            docker rm backend-app || true

            echo "📥 Pull new image from DockerHub"
            docker pull volodymyrsulik/backend:latest

            echo "🚀 Start new container"
            docker run -d -p 80:8080 \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              --name backend-app \
              volodymyrsulik/backend:latest
