name: Backend CI

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build project
        run: yarn build
