name: Deploy Backend to EC2

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🧹 Stop old docker container (if exist)"
            docker stop backend-app || true
            docker rm backend-app || true

            echo "📥 Download latest version from DockerHub"
            docker pull volodymyrsulik/backend:latest

            echo "🚀 Start new container"
            docker run -d -p 80:8080 \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              --name backend-app \
              volodymyrsulik/backend:latest
